version: '3.8'

services:
  lab02:
    build: 
      context: .
      dockerfile: Dockerfile
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,graphics
      - MUJOCO_GL=egl
      - XLA_PYTHON_CLIENT_PREALLOCATE=false
      - XLA_FLAGS=--xla_gpu_triton_gemm_any=True
      - DISPLAY=${DISPLAY}
    volumes:
      - .:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 2G
    working_dir: /workspace
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    # Override the default command to keep container running
    command: bash